In [ ]:
#create a numpy arrary containing numbers from 1 to 20 using in built functions
import numpy as np
array = np.arange(1, 21)
print(array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
#create an array of all zeroes with 10 elements and convert it to matrix
import numpy as np
zero = np.zeros((5,2))
print(zero)
matrix=np.reshape(zero,(10,1))
print(matrix)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [ ]:
#create an array containing even numbers from 2 to 20
import numpy as np
even=np.arange(2,21,2)
print(even)

[ 2  4  6  8 10 12 14 16 18 20]


In [ ]:
#create an array and find no of dimensions,shape,size,datatype and multiply every element by 2
import numpy as np
array1=[2,4,6,8]
array2=[3,5,7,9]
dimension=np.shape(array1)
print(dimension)
shape=np.shape(array1)
print(shape)
size=np.size(array1)
print(size)
#atatype=array1.dtype
#print(datatype)
multiply=array1*2
print(multiply)


(4,)
(4,)
4
[2, 4, 6, 8, 2, 4, 6, 8]


In [ ]:
#create 1d array and find sum,mean, maximum, minimum values
import numpy as np
array1=[2,4,6,8]
sum=np.sum(array1)
print(sum)
mean=np.mean(array1)
print(mean)
maximum=np.max(array1)
print(maximum)
minimum=np.min(array1)
print(minimum)

20
5.0
8
2
