In [18]:
#importing
import numpy as np
arr1 = ([1,2,3,4])
print(arr1)
arr2 = ([1,2,3,4],[5,6,7,8])
print(arr2)

[1, 2, 3, 4]
([1, 2, 3, 4], [5, 6, 7, 8])


In [2]:
zero = np.zeros((2,3))
print('zero array : ',zero)

zero array :  [[0. 0. 0.]
 [0. 0. 0.]]


In [3]:
one = np.ones((3,3))
print('ones array : ',one)

ones array :  [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [4]:
identity = np.eye(4,4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [5]:
#linespace
ls = np.linspace(1,3,5)
print(ls)

[1.  1.5 2.  2.5 3. ]


In [6]:
#random numbers
randnum = ((np.random.rand(2,3))*10).astype(int)
print(randnum)

[[8 6 6]
 [7 4 5]]


In [7]:
ashp = np.shape(arr2)
print(ashp)

(2, 4)


In [8]:
arr = np.arange(2,10).reshape(4,2)
print(arr)

[[2 3]
 [4 5]
 [6 7]
 [8 9]]


In [17]:
array1 = ([1,2,3,4],[5,6,7,8])
array2 = ([4,6,8,3],[2,5,7,9])



In [16]:
#sum
print("Sum:", np.sum(arr))

Sum: 44


In [24]:
#Mean
Mean = np.mean(array1)
print(Mean)

4.5


In [23]:
#standard deviation
standard = np.std(array1)
print(standard)

2.29128784747792


In [22]:
#aggregate functions
Min = np.min(array1)
print(Min)
Max = np.max(array1)
print(Max)
ArgMin = np.argmin(array1)
print(ArgMin)
ArgMax = np.argmax(array1)
print(ArgMax)

1
8
0
7


In [21]:
#matrix multiplication
X = np.array(([3,4],[5,6]))
Y = np.array(([8,9],[6,7]))
Dot = np.dot(X,Y)
print(Dot)

[[48 55]
 [76 87]]


In [20]:
#reshape and transpose
mat = np.arange(2,10).reshape(2,4)
print(mat)
print(mat.T)

[[2 3 4 5]
 [6 7 8 9]]
[[2 6]
 [3 7]
 [4 8]
 [5 9]]


In [19]:
#sorting
sorts = np.sort(array2)
print(sorts)

[[3 4 6 8]
 [2 5 7 9]]
